name: run main.py

on: 
  workflow_dispatch:
  schedule:
    - cron: '23 12 * * *'

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          pip install pandas
          pip install frictionless

      - name: Run main.py
        run: python main.py
        

      - name: commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update generated JSON [skip ci]"
            git push
          fi

  deploy-pages:
    needs: generate-json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
