name: run main.py

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name'
        required: true

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pip install bs4
          pip install pip install pandas
          pip install pip install frictionless

      - name: Run main.py
        run: python main.py

      #- name: Move generated JSON to files folder
      #  run: mv output.json files/output.json

      - name: commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update generated JSON [skip ci]"
            git push
          fi

  deploy-pages:
    needs: generate-json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: github pages link
        run: |
          echo "GitHub Pages URL: https://${{ env.REPO_OWNER }}.github.io/${{ env.REPO_NAME }}"
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
